name = "paperplane"

compatibility_date = "2024-05-02"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"


[[kv_namespaces]]
binding = "KV_TEST"
id = "cccf0bba83a64d1c9ed149ed475bc1fa"