name = "paperplane"

compatibility_date = "2024-05-02"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"


[[kv_namespaces]]
binding = ""
id = ""

[vars]
PASSWD = '' 
JWT_SECRET_KEY = ''
R2_ACCOUNT_ID=''
R2_ACCESS_KEY_ID=''
R2_SECRET_KEY_ID=''
R2_BUCKET_NAME=''
PUBLIC_R2_URL=''
